TRACKED_LEAGUES = [
    "NHL", "SHL", "LIIGA", "NLA",
    "MLB", "NBA",
    "PREMIER LEAGUE", "LIGUE 1", "SERIE A", "BUNDESLIGA",
    "LA LIGA", "BRASILEIRAO", "LIGA PROFESSIONAL",
    "ALLSVENSKAN", "ELITESERIEN", "SUPER LIG", "SUPER LIIGA", "VEIKKAUSLIIGA", "EREDIVISIE"
]

ODDS_BASE_THRESHOLD = 2.00
ALERT_INCREASE_20 = 0.20
ALERT_INCREASE_50 = 0.50
